export async function seed(knex) {
  await knex("users").del();
  await knex("users").insert([
    {
      id: 1,
      user_name: "Alice Johnson",
      user_email: "alice.johnson@example.com",
      phone_number: "123-456-7890",
    },
    {
      id: 2,
      user_name: "Bob Smith",
      user_email: "bob.smith@example.com",
      phone_number: "234-567-8901",
    },
    {
      id: 3,
      user_name: "Charlie Brown",
      user_email: "charlie.brown@example.com",
      phone_number: "345-678-9012",
    },
    {
      id: 4,
      user_name: "Diana Prince",
      user_email: "diana.prince@example.com",
      phone_number: "456-789-0123",
    },
    {
      id: 5,
      user_name: "Ethan Hunt",
      user_email: "ethan.hunt@example.com",
      phone_number: "567-890-1234",
    },
    {
      id: 6,
      user_name: "Fiona Gallagher",
      user_email: "fiona.gallagher@example.com",
      phone_number: "678-901-2345",
    },
    {
      id: 7,
      user_name: "George Lucas",
      user_email: "george.lucas@example.com",
      phone_number: "789-012-3456",
    },
    {
      id: 8,
      user_name: "Hannah Montana",
      user_email: "hannah.montana@example.com",
      phone_number: "890-123-4567",
    },
    {
      id: 9,
      user_name: "Ian Malcolm",
      user_email: "ian.malcolm@example.com",
      phone_number: "901-234-5678",
    },
    {
      id: 10,
      user_name: "Jessica Jones",
      user_email: "jessica.jones@example.com",
      phone_number: "012-345-6789",
    },
    {
      id: 11,
      user_name: "Kevin Hart",
      user_email: "kevin.hart@example.com",
      phone_number: "123-456-7891",
    },
    {
      id: 12,
      user_name: "Laura Croft",
      user_email: "laura.croft@example.com",
      phone_number: "234-567-8902",
    },
    {
      id: 13,
      user_name: "Michael Scott",
      user_email: "michael.scott@example.com",
      phone_number: "345-678-9013",
    },
    {
      id: 14,
      user_name: "Nina Simone",
      user_email: "nina.simone@example.com",
      phone_number: "456-789-0124",
    },
    {
      id: 15,
      user_name: "Oscar Isaac",
      user_email: "oscar.isaac@example.com",
      phone_number: "567-890-1235",
    },
    {
      id: 16,
      user_name: "Peter Parker",
      user_email: "peter.parker@example.com",
      phone_number: "678-901-2346",
    },
    {
      id: 17,
      user_name: "Quinn Fabray",
      user_email: "quinn.fabray@example.com",
      phone_number: "789-012-3457",
    },
    {
      id: 18,
      user_name: "Rachel Green",
      user_email: "rachel.green@example.com",
      phone_number: "890-123-4568",
    },
    {
      id: 19,
      user_name: "Steve Rogers",
      user_email: "steve.rogers@example.com",
      phone_number: "901-234-5679",
    },
    {
      id: 20,
      user_name: "Tina Fey",
      user_email: "tina.fey@example.com",
      phone_number: "012-345-6780",
    },
    {
      id: 21,
      user_name: "Ursula K. Le Guin",
      user_email: "ursula.leguin@example.com",
      phone_number: "123-456-7892",
    },
    {
      id: 22,
      user_name: "Victor Hugo",
      user_email: "victor.hugo@example.com",
      phone_number: "234-567-8903",
    },
    {
      id: 23,
      user_name: "Wanda Maximoff",
      user_email: "wanda.maximoff@example.com",
      phone_number: "345-678-9014",
    },
    {
      id: 24,
      user_name: "Xena Warrior",
      user_email: "xena.warrior@example.com",
      phone_number: "456-789-0125",
    },
    {
      id: 25,
      user_name: "Yoda",
      user_email: "yoda@example.com",
      phone_number: "567-890-1236",
    },
    {
      id: 26,
      user_name: "Zoe Saldana",
      user_email: "zoe.saldana@example.com",
      phone_number: "678-901-2347",
    },
    {
      id: 27,
      user_name: "Aaron Paul",
      user_email: "aaron.paul@example.com",
      phone_number: "789-012-3458",
    },
    {
      id: 28,
      user_name: "Beth Harmon",
      user_email: "beth.harmon@example.com",
      phone_number: "890-123-4569",
    },
    {
      id: 29,
      user_name: "Cleo de Nile",
      user_email: "cleo.nile@example.com",
      phone_number: "901-234-5670",
    },
    {
      id: 30,
      user_name: "Drew Barrymore",
      user_email: "drew.barrymore@example.com",
      phone_number: "012-345-6781",
    },
  ]);
}
